---
- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-software-properties

- name: debian | adding glusterfs apt repo key
  apt_key:
    keyserver: "{{ glusterfs_debian_repo_info.keyserver }}"
    id: "{{ glusterfs_debian_repo_info.id }}"
    state: present

- name: debian | adding glusterfs apt repo
  apt_repository:
    repo: '{{ glusterfs_debian_repo_info.repo }}'
    state: present
