---
- name: debian | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-software-properties
    - xfsprogs

- name: debian | adding glusterfs apt repo key
  apt_key:
    keyserver: "{{ glusterfs_debian_repo_info.keyserver }}"
    id: "{{ glusterfs_debian_repo_info.id }}"
    state: present

- name: debian | adding glusterfs apt repo
  apt_repository:
    repo: '{{ glusterfs_debian_repo_info.repo }}'
    state: present

- name: debian | installing glusterfs server
  apt:
    name: "glusterfs-server"
    state: present
  when: inventory_hostname in groups[glusterfs_server_group]

- name: debian | installing glusterfs client
  apt:
    name: "glusterfs-client"
    state: present
  when: inventory_hostname in groups[glusterfs_client_group]

- name: debian | enabling glusterfs-server
  service:
    name: "glusterfs-server"
    enabled: yes
  when: inventory_hostname in groups[glusterfs_server_group]
