---
# tasks file for ansible-glusterfs
- include: config_lvm.yml
  when: glusterfs_config_lvm is defined and glusterfs_config_lvm

- include: update_etc_hosts.yml
  when: config_hosts is defined and config_hosts

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: config_glusterfs.yml
  when: config_glusterfs
