---
# tasks file for ansible-glusterfs
- include: config_lvm.yml
  when: >
        (glusterfs_config_lvm is defined and
        glusterfs_config_lvm) and
        inventory_hostname in groups[glusterfs_server_group]

- include: update_etc_hosts.yml
  tags:
    - update_etc_hosts
  when: >
        config_hosts is defined and
        config_hosts

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: config_glusterfs_server.yml
  when: >
        inventory_hostname in groups[glusterfs_server_group] and
        config_glusterfs

- include: config_glusterfs_client.yml
  when: >
        inventory_hostname in groups[glusterfs_client_group] and
        config_glusterfs
