---
- name: update_etc_hosts | updating /etc/hosts in case of dns lookup issues
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth0.ipv4.address }} {{ item }}" state=present
  with_items: groups['{{ server_group }}']
  when: glusterfs_repl_int == "eth0"

- name: update_etc_hosts | updating /etc/hosts in case of dns lookup issues
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{ item }}" state=present
  with_items: groups['{{ server_group }}']
  when: glusterfs_repl_int == "eth1"

- name: update_etc_hosts | updating /etc/hosts in case of dns lookup issues
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth2.ipv4.address }} {{ item }}" state=present
  with_items: groups['{{ server_group }}']
  when: glusterfs_repl_int == "eth2"
