---
- name: update_etc_hosts | updating /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_ssh_host }} {{ item }} {{ item }}.{{ pri_domain_name }}"
    line: "{{ hostvars[item].ansible_ssh_host }} {{ item }} {{ item }}.{{ pri_domain_name }}"
    state: present
  with_items: groups[glusterfs_nodes_group]
