---
#- name: update_etc_hosts | updating /etc/hosts
#  lineinfile:
#    dest: /etc/hosts
#    regexp: "^{{ hostvars[item].ansible_ssh_host }} {{ item }} {{ item }}.{{ pri_domain_name }}"
#    line: "{{ hostvars[item].ansible_ssh_host }} {{ item }} {{ item }}.{{ pri_domain_name }}"
#    state: present
#  with_items: groups[glusterfs_nodes_group]
#  when: pri_domain_name is defined

#- name: update_etc_hosts | updating /etc/hosts
#  lineinfile:
#    dest: /etc/hosts
#    regexp: "^{{ hostvars[item].ansible_ssh_host }} {{ item }}"
#    line: "{{ hostvars[item].ansible_ssh_host }} {{ item }}"
#    state: present
#  with_items: groups[glusterfs_nodes_group]
#  when: pri_domain_name is not defined

- name: update_etc_hosts | updating /etc/hosts
  template:
    src: "etc/hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644
